/* Editorial Signal: auth is a quiet split-screen threshold into the same warm-paper Jobflow workspace. */
import { FormEvent, useState } from "react";
import { ArrowUpRight, Check, Loader2, LockKeyhole } from "lucide-react";
import { Link, useLocation } from "wouter";

const mark="/jobflow-mark.svg";
const desk="/jobflow-editorial-desk.svg";

export default function Auth(){
  const [,setLocation]=useLocation();
  const mode=new URLSearchParams(window.location.search).get("mode")==="signup"?"signup":"login";
  const [isSignup,setIsSignup]=useState(mode==="signup");
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState("");
  const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  const submit=(e:FormEvent)=>{e.preventDefault();setError("");if(isSignup&&!name.trim()){setError("Add a name so your workspace knows what to call you.");return}if(!/^\S+@\S+\.\S+$/.test(email)){setError("Enter a valid email address to continue.");return}if(password.length<8){setError("Use at least 8 characters for your password.");return}setLoading(true);setTimeout(()=>{localStorage.setItem("jobflow-authenticated","true");setLocation("/app")},650)};
  return <div className="auth-page"><section className="auth-art"><div className="auth-art-top"><Link href="/" className="public-brand"><img src={mark} alt="Jobflow mark"/><span>jobflow</span></Link><span className="auth-folio">PRIVATE / BY DESIGN</span></div><div className="auth-art-copy"><div className="eyebrow">A clearer place to begin</div><h1>Make the work<br/><em>count twice.</em></h1><p>Capture the thinking behind your next move, then turn it into momentum you can see.</p></div><img className="auth-art-image" src={desk} alt="Editorial career planning desk"/><div className="auth-art-stamp">01<br/><span>your signal</span></div></section><section className="auth-form-side"><div className="auth-form-wrap"><Link href="/" className="auth-mobile-brand public-brand"><img src={mark} alt="Jobflow mark"/><span>jobflow</span></Link><div className="auth-kicker"><LockKeyhole size={13}/> Your data stays yours</div><h2>{isSignup?"Start with a clearer signal.":"Pick up where you left off."}</h2><p className="auth-lede">{isSignup?"Build a private workspace for the decisions that move your career forward.":"Your workspace is waiting — calm, focused, and ready for the next move."}</p><form onSubmit={submit} noValidate>{isSignup&&<label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" autoComplete="name"/></label>}<label>Email<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" type="email" autoComplete="email"/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} placeholder="8+ characters" type="password" autoComplete={isSignup?"new-password":"current-password"}/></label>{error&&<p className="auth-error"><span/> {error}</p>}<button className="button button--lime auth-submit" disabled={loading}>{loading?<><Loader2 size={16} className="spin"/> Opening your workspace…</>:<>{isSignup?"Create workspace":"Log in"}<ArrowUpRight size={16}/></>}</button></form><div className="auth-divider"><span/> or continue with <span/></div><button type="button" className="auth-secondary" onClick={()=>{setError("Social sign-in is not connected in this local preview.")}}>Continue with Google <ArrowUpRight size={14}/></button><p className="auth-toggle">{isSignup?"Already have a workspace?":"New to Jobflow?"} <button onClick={()=>{setIsSignup(!isSignup);setError("")}}>{isSignup?"Log in":"Create an account"} <ArrowUpRight size={13}/></button></p><p className="auth-footnote"><Check size={13}/> By continuing, you agree to keep your workspace grounded in your own information.</p></div></section></div>
}
