/* Editorial Signal behavior layer: preserves the existing visual system while providing persisted, cross-tab product state. */
import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type TabKey = "dashboard" | "copilot" | "jobs" | "applications" | "resume" | "cover" | "gaps" | "match" | "readiness" | "settings";
export type Job = { id:string; company:string; role:string; place:string; remote:"Remote"|"Hybrid"|"On-site"; experience:"Entry"|"Mid"|"Senior"; salary:number; skills:string[]; url:string; saved:boolean };
export type Application = { id:string; jobId:string; stage:"Saved"|"Applied"|"Interview"|"Offer"; followUp:string; notes:string };
export type ResumeVersion = { id:string; name:string; score:number; ats:number; text:string };
export type Letter = { id:string; jobId:string; resumeId:string; title:string; body:string };
export type CopilotMessage = { role:"user"|"assistant"; text:string };

type State = { profile:{name:string; title:string}; locationPreference:string; aiControls:{showSamples:boolean; useResumeContext:boolean}; targetRole:string; jobs:Job[]; applications:Application[]; resumes:ResumeVersion[]; letters:Letter[]; threads:{id:string; title:string; messages:CopilotMessage[]}[]; activeThread:string; viewedJobId:string; copilotContext:{resume:boolean; job:boolean; gaps:boolean}; gapRole:string; gapDone:string[]; settingsTab:string };
const seedJobs:Job[] = [
 {id:"northstar",company:"Northstar Labs",role:"Product Designer",place:"New York",remote:"Hybrid",experience:"Senior",salary:145000,skills:["Research","Prototyping","Systems thinking"],url:"https://www.linkedin.com/jobs/",saved:false},
 {id:"archive",company:"Archive Systems",role:"Senior UX Researcher",place:"United States",remote:"Remote",experience:"Senior",salary:138000,skills:["Research","Analytics","Synthesis"],url:"https://www.linkedin.com/jobs/",saved:false},
 {id:"fieldnotes",company:"Field Notes Co.",role:"Design Operations Lead",place:"Chicago",remote:"On-site",experience:"Mid",salary:118000,skills:["Design ops","Systems thinking","Planning"],url:"https://www.linkedin.com/jobs/",saved:false}
];
const initial:State={profile:{name:"",title:""},locationPreference:"",aiControls:{showSamples:true,useResumeContext:true},targetRole:"Product Designer",jobs:seedJobs,applications:[],resumes:[],letters:[],threads:[{id:"welcome",title:"First steps with Copilot",messages:[{role:"assistant",text:"Your context is empty for now. Add a resume or ask a general career question to begin."}]}],activeThread:"welcome",viewedJobId:"northstar",copilotContext:{resume:false,job:false,gaps:false},gapRole:"Product Designer",gapDone:[],settingsTab:"Profile"};
const key="jobflow-state-v1";
function load(){try{const saved=JSON.parse(localStorage.getItem(key)||"{}");return {...initial,...saved,profile:{...initial.profile,...saved.profile},aiControls:{...initial.aiControls,...saved.aiControls}} as State}catch{return initial}}
type Ctx = State & { setProfile:(p:Partial<State["profile"]>)=>void; setPreferences:(p:{locationPreference?:string})=>void; setAiControls:(p:Partial<State["aiControls"]>)=>void; setTargetRole:(r:string)=>void; setViewedJob:(id:string)=>void; newThread:()=>void; toggleSave:(id:string)=>void; addApplication:(jobId:string)=>void; moveApplication:(id:string,stage:Application["stage"])=>void; updateApplication:(id:string,p:Partial<Application>)=>void; addResume:(r:ResumeVersion)=>void; saveLetter:(l:Letter)=>void; sendMessage:(text:string)=>void; setActiveThread:(id:string)=>void; toggleContext:(k:keyof State["copilotContext"])=>void; toggleGap:(s:string)=>void; setSettingsTab:(s:string)=>void; resetData:()=>void };
const JobflowContext=createContext<Ctx|null>(null);
export function JobflowProvider({children}:{children:ReactNode}){const [state,setState]=useState<State>(load);useEffect(()=>localStorage.setItem(key,JSON.stringify(state)),[state]);const api=useMemo<Ctx>(()=>({...state,setProfile:p=>setState(s=>({...s,profile:{...s.profile,...p}})),setPreferences:p=>setState(s=>({...s,...p})),setAiControls:p=>setState(s=>({...s,aiControls:{...s.aiControls,...p}})),setTargetRole:r=>setState(s=>({...s,targetRole:r,gapRole:r})),setViewedJob:id=>setState(s=>({...s,viewedJobId:id})),newThread:()=>setState(s=>{const id=`thread-${Date.now()}`;return {...s,activeThread:id,threads:[...s.threads,{id,title:"New career conversation",messages:[{role:"assistant",text:"New conversation started. Ask about your next move."}]}]}}),toggleSave:id=>setState(s=>({...s,jobs:s.jobs.map(j=>j.id===id?{...j,saved:!j.saved}:j)})),addApplication:jobId=>setState(s=>s.applications.some(a=>a.jobId===jobId)?s:{...s,applications:[...s.applications,{id:`app-${Date.now()}`,jobId,stage:"Saved",followUp:"",notes:""}]}),moveApplication:(id,stage)=>setState(s=>({...s,applications:s.applications.map(a=>a.id===id?{...a,stage}:a)})),updateApplication:(id,p)=>setState(s=>({...s,applications:s.applications.map(a=>a.id===id?{...a,...p}:a)})),addResume:r=>setState(s=>({...s,resumes:[...s.resumes,r],copilotContext:{...s.copilotContext,resume:true}})),saveLetter:l=>setState(s=>({...s,letters:[...s.letters.filter(x=>x.id!==l.id),l]})),sendMessage:text=>setState(s=>{const t=s.threads.find(x=>x.id===s.activeThread)||s.threads[0];const reply=`Illustrative response: I’d start by grounding this in your real resume, target role, and evidence. For now, your question is: “${text}”`;return {...s,threads:s.threads.map(x=>x.id===t.id?{...x,messages:[...x.messages,{role:"user",text},{role:"assistant",text:reply}]}:x)};}),setActiveThread:id=>setState(s=>({...s,activeThread:id})),toggleContext:k=>setState(s=>({...s,copilotContext:{...s.copilotContext,[k]:!s.copilotContext[k]}})),toggleGap:skill=>setState(s=>({...s,gapDone:s.gapDone.includes(skill)?s.gapDone.filter(x=>x!==skill):[...s.gapDone,skill]})),setSettingsTab:s=>setState(x=>({...x,settingsTab:s})),resetData:()=>setState(initial)}),[state]);return <JobflowContext.Provider value={api}>{children}</JobflowContext.Provider>}
export function useJobflow(){const c=useContext(JobflowContext);if(!c)throw new Error("useJobflow must be inside JobflowProvider");return c}
